spring.application.name=nextcode

spring.datasource.url=jdbc:postgresql://localhost:5456/nextcode
spring.datasource.username=nextcode
spring.datasource.password=1111

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.flyway.enabled=true

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

spring.security.enabled=false

server.address=0.0.0.0
server.port=8080